apiVersion: v1
kind: Secret
metadata:
    name: linkding-oidc-secret
    namespace: linkding
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:3oGA/0CCa3eUVNyA5E6fvE+ZgWtvzDcHkXO/fdGCkz2ZkSySwwL3aqUHSQ==,iv:TSODOUFtDTp4eCFJoyrtT5ZU71meBqxMYN4ZJpUiRHA=,tag:gNccHfg3hbWTmlMok8YZ8A==,type:str]
sops:
    age:
        - recipient: age1skcq3r4efnczz0h04wv9978yld2mgty6cfzmv4vfdvl6yjqg83kqastcce
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRlpmYVEvUmc5UE1FcTYr
            WTNVRiswc1kzQlhqOTloTXpSZ3haMVJrWmtnCllVRVJ5UE4vaTc3ZmQwZTZWeVJT
            a2xGUDhEV3VqV3VqYUl1SzRDNmZQcDgKLS0tIDg3S0hXSHJwTEZGRWF1eHlIWE1N
            aDZvalNsWTFaQldoSjZGN1dTRzJwV2MKhSQgA5c0qkXcrYQahSfJn/9h923x9+1R
            kVsxBu9+Z0Mc1pEElyMEvhlDQDS8VgmK50oQUwLZdxJFq6IsdVJhwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-18T14:49:16Z"
    mac: ENC[AES256_GCM,data:5ruqMDi3HNxVElRTeRmxpCAaUpNPXS9SCiY14IbEuPABcNyyJ22qUzUcNLgSEkC/H17+WndT/EyvXkieDsIP+C9bch6xjbBJWoLrDWYi69qzgKQ9tBg8w91E74wbyr/rsO1+CUB5oaIQl5mPPDjvWTnzbMynOXiGcKDs7yq3f+Q=,iv:9VZD6B93Ys2E4T7Ri4BCsRAP43P8pjs7h+hwfmCSPYs=,tag:WQ+q56m0wdKpw6ybrkfAyw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
