apiVersion: v1
kind: Secret
metadata:
    name: filebrowser-oidc-secret
    namespace: filebrowser
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:SVhD4lRp9wp6SffsZYcZqMd9lrjffufXPTw3XP6d+cFlSRdP6tQQCtrqGg==,iv:VlDlBPwxyfXgC4khnvrrz7vhbnBI1JQwuvTzSc3HKdw=,tag:tkPwz0RlCPL8K2ZowHDPfQ==,type:str]
sops:
    age:
        - recipient: age1skcq3r4efnczz0h04wv9978yld2mgty6cfzmv4vfdvl6yjqg83kqastcce
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaVlRERkdKMCtBWUxkN1Mw
            UmxGbXI5MjBtNEYwbEZWRmVEbjcvS0oyVVNJCkJkamxPTi95OHZtR1ZVNmV3UlpW
            TmxacHFVOW54WDRBbDUybGoraFhOeVEKLS0tIENSMEVZMWovNTMwV2UwUk9iUCtz
            OU1BMm8xdENLMnI0TW85MTNRTEpmYU0KNL1eGKgNxI11ofcLC2Xy4uuBYrpJtePM
            pWR3kSZZ7jAfzkw5Mu9JmwY8TggMbr/LM5NBzZy5+vRSGU3bsaQ1Ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-18T14:49:16Z"
    mac: ENC[AES256_GCM,data:DTvP2pqfXiS1NGDNzRdiDu23q3U8fQ0hrc8lA2X1r/tB/l5fltWg1fGK1j/rX8DEt1MsZew35CWmigqOFOS1QLbZX1aS+v7QwExZIGs7LsV4Vr/0MLgVGCTZBp8RpWoK+iI9OXkbbahMlDVL6yo3m7ZCJzG79iNDjIuhUmeZUiY=,iv:CIgQXEwq+53hEZDOrsZ3RUYIqfxjYPTLz0jNu5NS8ks=,tag:TAocUhn0i12JDX4MmBWflg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
