---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo
  namespace: forgejo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forgejo
  template:
    metadata:
      labels:
        app: forgejo
    spec:
      containers:
        - name: forgejo
          image: codeberg.org/forgejo/forgejo:9
          env:
            - name: USER_UID
              value: "1000"
            - name: USER_GID
              value: "1000"
            - name: FORGEJO__server__DOMAIN
              value: git.home.arpa
            - name: FORGEJO__server__ROOT_URL
              value: "https://git.home.arpa"
            - name: FORGEJO__database__DB_TYPE
              value: sqlite3
            - name: FORGEJO__security__INSTALL_LOCK
              value: "true"
            - name: FORGEJO__security__SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: forgejo-secret
                  key: secret-key
            - name: FORGEJO__service__DISABLE_REGISTRATION
              value: "true"
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 20m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: forgejo-data
