---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logging
resources:
  - ../../base/logging
patches:
  - path: loki-release.yaml
    target:
      kind: HelmRelease
      name: loki
