---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: logging
spec:
  releaseName: loki
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: logging
  interval: 50m
  values:
    gateway:
      service:
        type: LoadBalancer
        loadBalancerIP: 192.168.0.233
