---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metrics
resources:
  - ../../base/metrics
patches:
  - path: prometheus-release.yaml
    target:
      kind: HelmRelease
