---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: promtail
  namespace: logging
spec:
  releaseName: promtail
  dependsOn:
    - name: loki
      namespace: logging
  chart:
    spec:
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: logging
  interval: 50m
