---
apiVersion: v1
kind: ConfigMap
metadata:
  name: existing-homepage-configmap
  namespace: homepage
data:
  settings.yaml: |
    headerStyle: boxed
  bookmarks.yaml: |
    {}
  widgets.yaml: |
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
    - search:
        provider: duckduckgo
        target: _blank
  services.yaml: |
    - Infrastructure:
      - Proxmox:
          icon: proxmox
          href: https://proxmox.home.arpa:8006
          description: Virtualization
      - Pi-hole:
          icon: pi-hole
          href: https://pihole.home.arpa/admin
          description: Network-wide Ad Blocking
      - Grafana:
          icon: grafana
          href: https://grafana.home.arpa/
          description: Analytics and Monitoring
      - Prometheus:
          icon: prometheus
          href: http://prometheus.home.arpa
          description: Metrics
      - Longhorn:
          icon: longhorn
          href: https://longhorn.home.arpa
          description: Distributed Storage
    - Apps:
      - Forgejo:
          icon: gitea
          href: https://git.home.arpa
          description: Git Server
      - Authelia:
          icon: authelia
          href: https://auth.home.arpa
          description: SSO / Identity Provider
      - Filebrowser:
          icon: filebrowser
          href: https://files.home.arpa
          description: File Manager
      - Jellyfin:
          icon: jellyfin
          href: https://jellyfin.home.arpa
          description: Media Server
      - Linkding:
          icon: linkding
          href: https://links.home.arpa
          description: Bookmark Manager
  kubernetes.yaml: |
    {}
  docker.yaml: |
    {}
