---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homepage
resources:
  - ../../base/homepage
  - configmap.yaml
  - service.yaml
patches:
  - path: env-patch.yaml
    target:
      kind: HelmRelease
      name: homepage
