---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage
spec:
  selector:
    app.kubernetes.io/instance: homepage
  type: LoadBalancer
  loadBalancerIP: 192.168.0.235
  loadBalancerSourceRanges:
    - 192.168.0.0/24
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
