---
grafana_ini:
  security:
    admin_user: admin
    # TODO: 修正
    admin_password: password
grafana_datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: 'http://localhost:9090'
