---
grafana_ini:
  security:
    admin_user: admin
    # TODO: 修正
    admin_password: password
  metrics:
    enabled: true
grafana_dashboards:
  - dashboard_id: 15489
    revision_id: 2
    datasource: prometheus
  - dashboard_id: 20138
    revision_id: 1
    datasource: prometheus
  - dashboard_id: 16450
    revision_id: 3
    datasource: prometheus-kube
  - dashboard_id: 15141
    revision_id: 1
    datasource: loki
grafana_datasources:
  - name: prometheus
    type: prometheus
    access: proxy
    url: 'http://localhost:9090'
  - name: prometheus-kube
    type: prometheus
    access: proxy
    url: 'http://192.168.0.232:9090'
  - name: loki
    type: loki
    access: proxy
    url: 'http://192.168.0.233'
