---
# FIXME: 所有者がrootのままのため。修正する
prometheus_system_group: 'root'
prometheus_scrape_configs:
  - job_name: "prometheus"
    metrics_path: "{{ prometheus_metrics_path }}"
    static_configs:
      - targets:
          - "{{ ansible_fqdn | default(ansible_host) | default('localhost') }}:9090"
  - job_name: "grafana"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["localhost:3000"]
