apiVersion: v1
kind: Secret
metadata:
    name: forgejo-oidc-secret
    namespace: forgejo
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:I0B1Oo+WxIZg+t3kbdAnv/0j+CcdEwtUv95O1JbKrCCNZG+qI5DBd5fs8A==,iv:FUWgRIQpk1trq8XvV+H3AtGyLSUVkEiDHuznFvudS/A=,tag:z5D4OZLz+8JVVEmcCa4cOg==,type:str]
sops:
    age:
        - recipient: age1skcq3r4efnczz0h04wv9978yld2mgty6cfzmv4vfdvl6yjqg83kqastcce
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBva0hKVVhXWGVCVGozdGwr
            MjJvUjRvTUsydGYxbzNoemcxek5OMHVMRVFVCml2UlAwa1RaMXdpYkZQblpCMGlq
            d2U4b3ZaTG43Ynd2dlhXRVNtMTQ2TjAKLS0tIGlwbElXc21UdFg1RmJQTEFJSVkx
            MG1rRWEyRGJ5YUxiVXgrbnBMNmozcWMKL700okKkM/msJjYybaYaj5EeJFHAHW4e
            JrbT+4+26+iqCWVkPT0u3+RK5v3rLrNKgb7nAbucxebmG9oKqfK5uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-18T14:49:16Z"
    mac: ENC[AES256_GCM,data:mYLXKa36jHkJ3tfzH6qYZ3ygSpy2g6KRzsrZRbv8TNL4++B+jACCaHpHZtraRHBid0abcpK4r6bAKhD0zBklxF18s0ZGIE+u5RojuuiZVL3X1qzRusqTfpuaNGGAPjvSTxKPBwzZdHT3t9wTv0c8u6cHnX/Nx5Z/eTfpWfpYlzs=,iv:LJuZOeqnQK5yQmFn2QJZ8l6FrCmyZYqYAjcA3Lq60P0=,tag:DXFJdMYMisrAS2hi8Hv7XQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
