apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secret
    namespace: forgejo
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:TwoROCRSNIgIeydb/McFnRdQv5jwAN5WMEXkSunG/sTRsQ6F4XaVhqcQ0+I=,iv:Lzp8qzQMphYJYjygfCXinfI/IwyFd9vKNvgQrhIZaao=,tag:GoSxEMkF8EG6tpIjerJohA==,type:str]
sops:
    age:
        - recipient: age1skcq3r4efnczz0h04wv9978yld2mgty6cfzmv4vfdvl6yjqg83kqastcce
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERGgyRVZhTmFyUDhNM0JC
            SmdiYXl2NmZ3MVJObFBZdHBCcHhtMWYzQ1VvCjJEOTJWc3JiRnFTMlFvNnFWL3d5
            Lzg5SDVRV3l2SGovNDY5ZDc1T1FSd2cKLS0tIEhHQmFTd1ZZc2ViL3VNb0piOHgr
            bkdwc2RMWkp2SFpGU01LOWhtaVhIK0kKdJJHWBHTEWO5YvpXwIfA7xA7hWx7TwfP
            SiYQsPnEb4XsMLjinav7FiO8Rv9YtP3RLkKOPi7kQkdBfrLPyDKqvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-16T15:37:07Z"
    mac: ENC[AES256_GCM,data:PMs5cWgnLU3ftry2V7NAzs1DEQUEjdkXHqR5pmnaQnQRjXsrkJeU/Hue/dZihguCgsXhboJTbSR5IBPC/85BJX72Yia6dB5P/NSA/sUndjOJIDp+YAqS9+q7XM+uR4wbWqNREuctkqU680/cgtQFTx/rbrrr5+U4k9OCTaTrQFM=,iv:bmdAkBaYXDgSx2Cs+JBYFCLtFpUwAM+RSjBgyR/8xL0=,tag:konCSDEYYzXRO1iOTxWdqQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
