---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia-config
  namespace: authelia
data:
  users_database.yml: |
    users:
      nakamura0907:
        displayname: nakamura0907
        password: '$argon2id$v=19$m=65536,t=3,p=4$Xf/H3wF10B+qK9yVhMykag$0J8wAQ3xKTeQNIC58AoMw6pk/0kZZIdiuIeYqMysqhw'
        email: nakamura0907@home.arpa
        groups:
          - admins
