---
# K3sクラスター
k3s_cluster:
  children:
    # K3sサーバー
    k3s_cluster_server:
      children:
        k3s_prod_cluster_server:
        k3s_stg_cluster_server:
    # K3sエージェント
    k3s_cluster_agent:
      children:
        k3s_prod_cluster_agent:
    # 運用K3sクラスター
    k3s_prod_cluster:
      children:
        k3s_prod_cluster_server:
          hosts:
            192.168.0.110:
        k3s_prod_cluster_agent:
          hosts:
            192.168.0.111:
            192.168.0.112:
    # 検証K3sクラスター
    k3s_stg_cluster:
      children:
        k3s_stg_cluster_server:
          hosts:
            192.168.0.120:
# 監視サーバー
monitoring:
  children:
    prometheus:
      hosts:
        192.168.0.214
