---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: metrics
spec:
  interval: 5m
  url: https://prometheus-community.github.io/helm-charts
