---
apiVersion: v1
kind: Service
metadata:
  name: pihole-service
  namespace: pihole
spec:
  selector:
    app: pihole
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
    - port: 53
      targetPort: 53
      nodePort: 30053
      protocol: TCP
    - port: 53
      targetPort: 53
      nodePort: 30053
      protocol: UDP
  type: NodePort
