---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
  interval: 50m
  values:
    crds:
      enabled: true
      # HelmRelease削除時もCRD(と発行済みCertificateリソース)を残す
      keep: true
