---
- name: K3s Cluster
  ansible.builtin.import_playbook: site_k3s.yml

- name: Monitoring
  ansible.builtin.import_playbook: site_monitoring.yml

- name: DNS
  ansible.builtin.import_playbook: site_dns.yml

- name: Exporters
  ansible.builtin.import_playbook: site_exporters.yml
