---
- name: Install Vault Vagrant Development Server
  hosts: secret_manager
  any_errors_fatal: true
  become: true
  become_user: root
  roles:
    - {role: ansible-community.ansible-vault, vault_backend: file}
