---
- name: Setup Prometheus
  hosts: prometheus
  roles:
    - prometheus.prometheus.prometheus

- name: Setup Grafana
  hosts: grafana
  roles:
    - grafana.grafana.grafana

- name: Setup TLS reverse proxy (Caddy)
  hosts: monitoring
  roles:
    - caddy
