---
- name: K3s Cluster
  ansible.builtin.import_playbook: site_k3s.yml

# Monitoring/DNSのCaddyがルートCA証明書を参照するため、PKIを先に実行する
- name: PKI
  ansible.builtin.import_playbook: site_pki.yml

- name: Monitoring
  ansible.builtin.import_playbook: site_monitoring.yml

- name: DNS
  ansible.builtin.import_playbook: site_dns.yml

- name: Exporters
  ansible.builtin.import_playbook: site_exporters.yml
