---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebrowser-config
  namespace: filebrowser
data:
  config.yaml: |
    server:
      cacheDir: /home/filebrowser/data/tmp
      sources:
        - path: /srv
          config:
            defaultEnabled: true
    auth:
      methods:
        oidc:
          enabled: true
          clientId: filebrowser
          issuerUrl: https://auth.home.arpa
          scopes: openid profile email groups
          userIdentifier: preferred_username
