---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homelab-ca
  namespace: linkding
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBqDCCAU2gAwIBAgIQf9Uh1BpSZX2LOrhhcQkPHTAKBggqhkjOPQQDAjAyMRMw
    EQYDVQQKEwpIb21lbGFiIENBMRswGQYDVQQDExJIb21lbGFiIENBIFJvb3QgQ0Ew
    HhcNMjYwNzA0MDYyMzM1WhcNMzYwNzAxMDYyMzM1WjAyMRMwEQYDVQQKEwpIb21l
    bGFiIENBMRswGQYDVQQDExJIb21lbGFiIENBIFJvb3QgQ0EwWTATBgcqhkjOPQIB
    BggqhkjOPQMBBwNCAASiQEuuKa+A46lZXoeXb10gjBYvDyJ/ejctyqNB1k0gZ8Wi
    A01zcJLNOruBh6VWK0vpzF8e636RE22w3wqUeTSLo0UwQzAOBgNVHQ8BAf8EBAMC
    AQYwEgYDVR0TAQH/BAgwBgEB/wIBATAdBgNVHQ4EFgQUKIs0FcJywPmiIzYz8V4F
    hSUI/GIwCgYIKoZIzj0EAwIDSQAwRgIhAP8Ys2ujJLNl8P8wcOL0qzIUCXuKyP53
    PDaJnPprXnwFAiEAw+9LRMhPg8ik+uLQbwyJfB36oxn+BguwJKSPg4ey6pU=
    -----END CERTIFICATE-----
